variable "cidr_block" {}
variable "env" {}
variable "eks_name" {}
variable "zone1" {}
variable "zone2" {}
variable "region" {}
variable "availability_zones" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "private_subnet_ids" {}
